apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: storage
spec:
  type: bindings.azure.blobstorage
  metadata:
  - name: storageAccount
    value: to-be-filled
  - name: storageAccessKey
    value: to-be-filled
  - name: container
    value: to-be-filled